[package]
name = "yaku_icons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
andrew = "0.3.1"
image = "0.23"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
indicatif = "0.16"
