
[[yaku]]
name = "Concealed Hand"
han = 1
closed_only = true

[[yaku]]
name = "Riichi"
han = 1
closed_only = true

[[yaku]]
name = "Ippsatsu"
han = 1
closed_only = true

[[yaku]]
name = "Pinfu"
han = 1
closed_only = true

[[yaku]]
name = "Pure Double Sequence"
han = 1
closed_only = true

[[yaku]]
name = "Under the Sea"
han = 1
closed_only = false

[[yaku]]
name = "Under the River"
han = 1
closed_only = false

[[yaku]]
name = "After a Kan"
han = 1
closed_only = false

[[yaku]]
name = "Robbing a Kan"
han = 1
closed_only = false

[[yaku]]
name = "All Simples"
han = 1
closed_only = false

[[yaku]]
name = "Yakuhai"
han = 1
closed_only = false

[[yaku]]
name = "Double Riichi"
han = 2
closed_only = true

[[yaku]]
name = "Half Outside Hand"
han = 1
closed_only = true
additional_on_closed = true

[[yaku]]
name = "Triple Sequence"
han = 1
closed_only = true
additional_on_closed = true

[[yaku]]
name = "Pure Straight"
han = 1
closed_only = false
additional_on_closed = true

[[yaku]]
name = "Toitoi"
han = 2
closed_only = false

[[yaku]]
name = "Triple Concealed Triplets"
han = 2
closed_only = false

[[yaku]]
name = "Triple Kan"
han = 2
closed_only = false

[[yaku]]
name = "Seven Pairs"
han = 2
closed_only = true

[[yaku]]
name = "Half Flush"
han = 2
closed_only = false
additional_on_closed = true

[[yaku]]
name = "Fully Outside Hand"
han = 2
closed_only = false
additional_on_closed = true

[[yaku]]
name = "Twice Pure Double Sequence"
han = 3
closed_only = true

[[yaku]]
name = "Full Flush"
han = 5
closed_only = false
additional_on_closed = true

[[yaku]]
name = "Blessing of Heaven"
han = 7
closed_only = false

[[yaku]]
name = "Blessing of Earth"
han = 7
closed_only = false

[[yaku]]
name = "Big Three Dragons"
han = 7
closed_only = false

[[yaku]]
name = "Little Three Dragons"
han = 2
closed_only = false

[[yaku]]
name = "Four Concealed Triplets"
han = 7
closed_only = true

[[yaku]]
name = "All Honors"
han = 7
closed_only = false

[[yaku]]
name = "All Green"
han = 7
closed_only = false

[[yaku]]
name = "Thirteen Orphans"
han = 7
closed_only = true

[[yaku]]
name = "Four Little Winds"
han = 7
closed_only = false

[[yaku]]
name = "Four Big Winds"
han = 7
closed_only = false

[[yaku]]
name = "Blessing of Man"
han = 5
closed_only = true

[[yaku]]
name = "All Terminals"
han = 7
closed_only = false

[[yaku]]
name = "Four Kan"
han = 7
closed_only = false

[[yaku]]
name = "Nine Gates"
han = 7
closed_only = true
